export const MOVIE_INFO_REQUEST = 'MOVIE_INFO_REQUEST';
export const MOVIE_INFO_RESPONSE = 'MOVIE_INFO_RESPONSE';
export const MOVIE_CAST_INFO_REQUEST = 'MOVIE_CAST_INFO_REQUEST';
export const MOVIE_CAST_INFO_RESPONSE = 'MOVIE_CAST_INFO_RESPONSE';
